added data for reviews
haikuacademy/B11G05-airbnb-react pull request #41
Opened 2024-03-02 06:56 UTC by Asayaobi

2024-03-02 07:07 UTC, tommypurcell requested changes
I think you should be able to just use one map and include all the elements content inside so you can use review.content or something else without doing another map.

2024-03-02 17:20 UTC, Asayaobi commented
Thank you Tommy, I made some changes to the code and also added some details for passing the data from houses component to reviews.

2024-03-03 02:59 UTC, tommypurcell requested changes
The reviews page is on the houses page. And there is an error on house page

2024-03-04 02:32 UTC, tommypurcell approved these changes

2024-03-04 02:32 UTC, merged